
% Renames confounds tsv file generated by fmriprep for compatibility with nibetaseries
% This step is necessary to run nibetaseries 0.6.0 as it expects the confounds tsv file to be named as xx_desc-confounds_regressors.tsv
% while fmriprep 20.2.3 generates confounds tsv files as xx_desc-confounds_timeseries.tsv

%Author: Aya Khalaf
%Date created: 09-18-2021

% BIDS path 
bids_dir = '/mnt/beegfs/XNAT/COGITATE/fMRI/phase_2/processed/bids';
% fMRIprep pre-processed fMRI data path
preprocessed_dir = '/mnt/beegfs/XNAT/COGITATE/fMRI/phase_2/processed/bids/derivatives/fmriprep';
%Subject list
tsv_data=tdfread(fullfile(bids_dir,'participants_fMRI_QC_included_phase3_sesV1.tsv'));
phase3_subjects = tsv_data.participant_id;
phase3_subjects = cellstr(phase3_subjects);
subject_list = cell2struct(phase3_subjects, 'name', length(phase3_subjects));

%Loop over subjects
for sub = 1:size(subject_list,1)
ID = subject_list(sub).name;
if (isfolder(fullfile(preprocessed_dir,ID)))
cd(fullfile(preprocessed_dir,ID,'ses-V1','func'))    
% Get all tsv files in the current folder
files = dir('*.tsv');
% Loop through files 
for id = 1:length(files)
      % Specify the new file name to be xx_desc-confounds_regressors.tsv
      new_file_name = strrep(files(id).name,'timeseries','regressors'); 
      % To revert back the changes, specify the new file name to be xx_desc-confounds_timeseries.tsv
      %new_file_name = strrep(files(id).name,'regressors','timeseries'); 
      % Rename confounds tsv
      movefile(files(id).name, new_file_name); 
end
end
end
